# Generated by Django 4.1.7 on 2023-03-07 10:42

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_picture_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='picture',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='picture',
            name='thumbnailUrl',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[100, 100], upload_to='thumbnails'),
        ),
    ]
